Redesign start and end date selection #123
tpcly/epsilon-lti pull request #136
Opened 2023-11-20 09:13 UTC by SaamieVincken

Redesign the current term date filter. 
> Move the logic to the searchbox and implement a "Custom" option

2023-11-23 13:55 UTC, NealGeilen requested changes
For me it is not working atm

2023-11-23 13:55 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/TopNavigation.vue
> +			<Col :cols="5">
Please make the cols 12 width in total

2023-11-29 23:18 UTC, NealGeilen requested changes

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
> +const isStatic = ref(false)
```suggestion
const isStatic = ref<boolean>(false)
```

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
> +const customClick = ref(false)
```suggestion
const customClick = ref<boolean>(false)
```

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
>  			:model-value="modelValue"
```suggestion
 			v-model="modelValue"
```

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
>  const query = ref("")
```suggestion
 const query = ref<string>("")
```

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
> +let datesAdjusted = false
```suggestion
const datesAdjusted = ref<boolean>(false)
```

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
>  function displayValue(item: { name: string }): string {
```suggestion
 function displayValue(term: EnrolmentTerm): string {
```

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/SearchBox.vue
> +.custom-box {
Just know that the amount of precies px used will not make the application responsive

2023-11-29 23:18 UTC, NealGeilen commented on Epsilon.Host.Frontend/src/components/TopNavigation.vue
> +	margin-right: 105px;
This moves the element to much. It's bad practice. It will not be responsive. And small changes will break the design quickly

2023-11-30 11:28 UTC, SaamieVincken commented
All feedback has been implemented

2023-11-30 23:47 UTC, NealGeilen approved these changes

2023-12-02 21:20 UTC, merged